### PR TITLE
fixed : 'CustomHTML2Text' is not defined

### PR DESCRIPTION
**Pull request by aadityakanjolia4**
The error has been fixed for synchronous crawling, which occurred after the latest push (version 0.3.73). "CustomHTML2Text" was previously defined incorrectly in the code, which prevented website crawling.

Solved issue: #248 

@unclecode

### CODE REVIEW

**Comment by unclecode** [comment]
Thank you for the pull request. This issue is actually fixed in the new version, which will be released in a day or two, using the same approach as the async version. I appreciate your effort and will add your name to our collaborator list. Please check the new version when it's released. Thank you.

**Comment by aadityakanjolia4** [comment]
Hi @unclecode ,

I hope you're doing well! I believe I might have been missed in being added as a contributor, as mentioned earlier. Could you kindly take a look when you have a moment?

Thank you!

**Comment by unclecode** [comment]
Apology, I will update the list by today. So sorry for that 🙏

**Comment by aadityakanjolia4** [comment]
@unclecode Gentle Reminder!!!

**Comment by unclecode** [comment]
@aadityakanjolia Please check the https://github.com/unclecode/crawl4ai/blob/main/CONTRIBUTORS.md btw, you are most welcome to join our discord, so I suggest share with me your email and I sent invitation.

**Comment by unclecode** [comment]
Will send soon

**Comment by aadityakanjolia4** [comment]
@unclecode please send link to join discord

**Pull request closed without merging**
