### PR TITLE
Add Browser Proxy Support, Enhance LLM Configuration, Fix Typos, and Remove Image Base64 URL Encoding

### PR DESCRIPTION
**Pull request by datehoer**
1. Browser proxy support to enable access to restricted websites in certain countries.
2. Introduce base_url configuration for LLMExtractionStrategy to allow flexible LLM endpoint management.
3. Correct prompt typos for better clarity and consistency.
4. HTML Base64 image URL encoding to optimize image handling and reduce payload size.
5. Updated the README to reflect new proxy settings and base_url configuration instructions.

### CODE REVIEW

**Comment by unclecode** [comment]
Hey @datehoer, well done! I really enjoyed your contribution to the codebase. Supporting the proxy has been in the backlog, and you just nailed it. Perfect. I love what you did and want to invite you to our Discord to be part of the initial contributors for Crawl for AI. We have long-term plans to really build this up, adding many more functionalities and making it one of the top options on Earth for AI crawling.

Again you made my day! I’m testing your changes in another branch, and I'll merge them into the main branch soon. Thank you so much. Let me know if you’re interested in joining our small team on Discord! May the code be with you

**Comment by datehoer** [comment]
ok,how to join the discord

**Comment by rangehow** [comment]
Great addition! When I tried to connect to a custom LLM endpoint, I realized there was no place to pass the base_url in the LLMExtractionStrategy. I'm glad to find it here. I hope this can be merged soon. :) Thank you again for your work.

**Comment by unclecode** [comment]
@datehoer @rangehow Please share with me the email address where you'd like me to send the Discord channel invitation. In the new version, which is scheduled for release by the end of this week, we are also including this proxy. Notably, we're switching to asynchronous while maintaining the synchronous version as well. The asynchronous version is significantly faster, and it also includes new features such as extracting JSON content without using a Large Language Model (LLM) via CSS selectors. This should be very helpful.

**Comment by rangehow** [comment]
> @datehoer @rangehow Please share with me the email address where you'd like me to send the Discord channel invitation. In the new version, which is scheduled for release by the end of this week, we are also including this proxy. Notably, we're switching to asynchronous while maintaining the synchronous version as well. The asynchronous version is significantly faster, and it also includes new features such as extracting JSON content without using a Large Language Model (LLM) via CSS selectors. This should be very helpful.请与我分享您希望我发送 Discord 频道邀请的电子邮件地址。在计划于本周末发布的新版本中，我们还包含了此代理。值得注意的是，我们正在切换到异步，同时也保持同步版本。异步版本的速度要快得多，并且它还包括新功能，例如通过 CSS 选择器提取 JSON 内容，而无需使用大型语言模型 （LLM）。这应该非常有帮助。

That would be so coool! : ) You can send invitation to rangehow@outlook.com

**Comment by datehoer** [comment]
> @datehoer @rangehow Please share with me the email address where you'd like me to send the Discord channel invitation. In the new version, which is scheduled for release by the end of this week, we are also including this proxy. Notably, we're switching to asynchronous while maintaining the synchronous version as well. The asynchronous version is significantly faster, and it also includes new features such as extracting JSON content without using a Large Language Model (LLM) via CSS selectors. This should be very helpful.

That is great! my email is datehoer@gmail.com, you can send invitation to it.

**Pull request merged**
